services:
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: metube
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mongodb_data:
