services:
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: metube
      MONGO_INITDB_ROOT_PASSWORD: ${METUBE_DB_PASSWORD}

  nginx:
    # image: nginx:alpine
    build: .
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/certs:ro
      - ./backend/static:/static
    ports:
      - "8000"

  app:
    build: ./backend
    environment:
      ROCKET_TEMP_DIR: "/cache"
      ROCKET_LIMITS: '{data-form="2147483648",file="2147483648"}'
      ROCKET_SECRET_KEY: ${METUBE_SECRET_KEY:?}
      ROCKET_DATABASES: "{metube={url=\"mongodb://metube:${METUBE_DB_PASSWORD:?}@db\"}}"
      ROCKET_LOG_LEVEL: ${METUBE_ROCKET_LOGLEVEL:-normal}
      ROCKET_ADDRESS: ${METUBE_HOST:-127.0.0.1}
      ROCKET_PORT: ${METUBE_PORT:-8000}
    volumes:
      - ${METUBE_UPLOAD:?}:/upload
      - ${METUBE_UPLOAD_CACHE:?}:/cache
      - ./MeTube.toml:/app/MeTube.toml
      - /mnt/temp:/mnt/temp

volumes:
  mongodb_data:
